#!/usr/bin/python3
import sys


def factorize(value):
    i = 2

    if value < i:
        return
    while value % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))


def main():
    if len(sys.argv) != 2:
        exit()

    try:
        with open(sys.argv[1]) as file:
            line = file.readline()

            while line != "":
                value = int(line.split('\n')[0])
                factorize(value)
                line = file.readline()
    except Exception:
        print("Exception: {}".format(sys.exc_info()[1]), file=sys.stderr)
    finally:
        print()

if __name__ == "__main__":
    main()
