#!/usr/bin/python3

import sys


def printer(num, i):
    print("{}={}*{}".format(num, num // i, i))


def main():
    try:
        with open(sys.argv[1]) as file:
            for num in file:
                num = int(num)
                if num % 2 == 0:
                    printer(num, 2)
                    continue
                i = 3
                while i < num // 2:
                    if num % i == 0:
                        printer(num, i)
                        break
                    i = i + 2
                if i == (num // 2) + 1:
                    printer(num, 1)
    except (IndexError):
        print("Exception: {}".format(sys.exc_info()[1]), file=sys.stderr)


if __name__ == "__main__":
    main()
